# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import (
    commerce_webhook_pb2 as commerce__webhook_dot_commerce__webhook__pb2,
)

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in commerce_webhook/commerce_webhook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommerceWebhookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertCommerceWebhookData = channel.unary_unary(
                '/commerce_webhook.CommerceWebhookService/InsertCommerceWebhookData',
                request_serializer=commerce__webhook_dot_commerce__webhook__pb2.InsertCommerceWebhookRequest.SerializeToString,
                response_deserializer=commerce__webhook_dot_commerce__webhook__pb2.InsertCommerceWebhookResponse.FromString,
                _registered_method=True)


class CommerceWebhookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertCommerceWebhookData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommerceWebhookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertCommerceWebhookData': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertCommerceWebhookData,
                    request_deserializer=commerce__webhook_dot_commerce__webhook__pb2.InsertCommerceWebhookRequest.FromString,
                    response_serializer=commerce__webhook_dot_commerce__webhook__pb2.InsertCommerceWebhookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'commerce_webhook.CommerceWebhookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('commerce_webhook.CommerceWebhookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommerceWebhookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertCommerceWebhookData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/commerce_webhook.CommerceWebhookService/InsertCommerceWebhookData',
            commerce__webhook_dot_commerce__webhook__pb2.InsertCommerceWebhookRequest.SerializeToString,
            commerce__webhook_dot_commerce__webhook__pb2.InsertCommerceWebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
