# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commerce_webhook/commerce_webhook.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    runtime_version as _runtime_version,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'commerce_webhook/commerce_webhook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import (
    struct_pb2 as google_dot_protobuf_dot_struct__pb2,
    timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'commerce_webhook/commerce_webhook.proto\x12\x10\x63ommerce_webhook\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x04\n\x1cInsertCommerceWebhookRequest\x12\x13\n\x06status\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08template\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x38\n\x12template_variables\x18\x03 \x01(\x0b\x32\x17.google.protobuf.StructH\x02\x88\x01\x01\x12\x18\n\x0b\x63ontact_urn\x18\x04 \x01(\tH\x03\x88\x01\x01\x12+\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x17.google.protobuf.StructH\x04\x88\x01\x01\x12*\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x17.google.protobuf.StructH\x05\x88\x01\x01\x12-\n\x04\x64\x61te\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x06\x88\x01\x01\x12\x14\n\x07project\x18\x08 \x01(\tH\x07\x88\x01\x01\x12-\n\x07request\x18\t \x01(\x0b\x32\x17.google.protobuf.StructH\x08\x88\x01\x01\x12.\n\x08response\x18\n \x01(\x0b\x32\x17.google.protobuf.StructH\t\x88\x01\x01\x12\x12\n\x05\x61gent\x18\x0b \x01(\tH\n\x88\x01\x01\x42\t\n\x07_statusB\x0b\n\t_templateB\x15\n\x13_template_variablesB\x0e\n\x0c_contact_urnB\x08\n\x06_errorB\x07\n\x05_dataB\x07\n\x05_dateB\n\n\x08_projectB\n\n\x08_requestB\x0b\n\t_responseB\x08\n\x06_agent\"/\n\x1dInsertCommerceWebhookResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x96\x01\n\x16\x43ommerceWebhookService\x12|\n\x19InsertCommerceWebhookData\x12..commerce_webhook.InsertCommerceWebhookRequest\x1a/.commerce_webhook.InsertCommerceWebhookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commerce_webhook.commerce_webhook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTCOMMERCEWEBHOOKREQUEST']._serialized_start=125
  _globals['_INSERTCOMMERCEWEBHOOKREQUEST']._serialized_end=694
  _globals['_INSERTCOMMERCEWEBHOOKRESPONSE']._serialized_start=696
  _globals['_INSERTCOMMERCEWEBHOOKRESPONSE']._serialized_end=743
  _globals['_COMMERCEWEBHOOKSERVICE']._serialized_start=746
  _globals['_COMMERCEWEBHOOKSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
