# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_templates.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    runtime_version as _runtime_version,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "message_templates.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17message_templates.proto\x12\x10message_template\x1a\x1cgoogle/protobuf/struct.proto"\x91\x02\n\x1cInsertMessageTemplateRequest\x12\x13\n\x0b\x63ontact_urn\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x15\n\rtemplate_name\x18\x04 \x01(\t\x12\x15\n\rtemplate_type\x18\x05 \x01(\t\x12\x13\n\x0btemplate_id\x18\x06 \x01(\t\x12\x12\n\nmessage_id\x18\x07 \x01(\t\x12\x11\n\tdirection\x18\x08 \x01(\t\x12\x1a\n\x12template_variables\x18\t \x01(\t\x12\x0c\n\x04text\x18\n \x01(\t\x12%\n\x04\x64\x61ta\x18\x0b \x01(\x0b\x32\x17.google.protobuf.Struct"/\n\x1dInsertMessageTemplateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t"\x84\x01\n"InsertMessageTemplateStatusRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x13\n\x0btemplate_id\x18\x03 \x01(\t\x12%\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct"5\n#InsertMessageTemplateStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa3\x02\n\x16\x44\x61talakeManagerService\x12|\n\x19InsertMessageTemplateData\x12..message_template.InsertMessageTemplateRequest\x1a/.message_template.InsertMessageTemplateResponse\x12\x8a\x01\n\x1bInsertMessageTemplateStatus\x12\x34.message_template.InsertMessageTemplateStatusRequest\x1a\x35.message_template.InsertMessageTemplateStatusResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "message_templates_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_INSERTMESSAGETEMPLATEREQUEST"]._serialized_start = 76
    _globals["_INSERTMESSAGETEMPLATEREQUEST"]._serialized_end = 349
    _globals["_INSERTMESSAGETEMPLATERESPONSE"]._serialized_start = 351
    _globals["_INSERTMESSAGETEMPLATERESPONSE"]._serialized_end = 398
    _globals["_INSERTMESSAGETEMPLATESTATUSREQUEST"]._serialized_start = 401
    _globals["_INSERTMESSAGETEMPLATESTATUSREQUEST"]._serialized_end = 533
    _globals["_INSERTMESSAGETEMPLATESTATUSRESPONSE"]._serialized_start = 535
    _globals["_INSERTMESSAGETEMPLATESTATUSRESPONSE"]._serialized_end = 588
    _globals["_DATALAKEMANAGERSERVICE"]._serialized_start = 591
    _globals["_DATALAKEMANAGERSERVICE"]._serialized_end = 882
# @@protoc_insertion_point(module_scope)
