# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

import datalake_manager.server.proto.message_template.message_templates_pb2 as message__templates__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in message_templates_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DatalakeManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertMessageTemplateData = channel.unary_unary(
            "/message_template.DatalakeManagerService/InsertMessageTemplateData",
            request_serializer=message__templates__pb2.InsertMessageTemplateRequest.SerializeToString,
            response_deserializer=message__templates__pb2.InsertMessageTemplateResponse.FromString,
            _registered_method=True,
        )
        self.InsertMessageTemplateStatusData = channel.unary_unary(
            "/message_template.DatalakeManagerService/InsertMessageTemplateStatusData",
            request_serializer=message__templates__pb2.InsertMessageTemplateStatusRequest.SerializeToString,
            response_deserializer=message__templates__pb2.InsertMessageTemplateStatusResponse.FromString,
            _registered_method=True,
        )


class DatalakeManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertMessageTemplateData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InsertMessageTemplateStatusData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DatalakeManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "InsertMessageTemplateData": grpc.unary_unary_rpc_method_handler(
            servicer.InsertMessageTemplateData,
            request_deserializer=message__templates__pb2.InsertMessageTemplateRequest.FromString,
            response_serializer=message__templates__pb2.InsertMessageTemplateResponse.SerializeToString,
        ),
        "InsertMessageTemplateStatusData": grpc.unary_unary_rpc_method_handler(
            servicer.InsertMessageTemplateStatusData,
            request_deserializer=message__templates__pb2.InsertMessageTemplateStatusRequest.FromString,
            response_serializer=message__templates__pb2.InsertMessageTemplateStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "message_template.DatalakeManagerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "message_template.DatalakeManagerService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DatalakeManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertMessageTemplateData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/message_template.DatalakeManagerService/InsertMessageTemplateData",
            message__templates__pb2.InsertMessageTemplateRequest.SerializeToString,
            message__templates__pb2.InsertMessageTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InsertMessageTemplateStatusData(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/message_template.DatalakeManagerService/InsertMessageTemplateStatusData",
            message__templates__pb2.InsertMessageTemplateStatusRequest.SerializeToString,
            message__templates__pb2.InsertMessageTemplateStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
